import 'package:flutter_application/features/search/model/theater_data.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
// required: associates our `main.dart` with the code generated by Freezed
part 'movie_airing_info.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'movie_airing_info.g.dart';

@Freezed(makeCollectionsUnmodifiable: false)
abstract class MovieAiringInfo with _$MovieAiringInfo {
  const MovieAiringInfo._();

  const factory MovieAiringInfo({
    @JsonKey(name: 'name') required String theaterName,
    @JsonKey(name: 'theater_id') required int theaterId,
    @JsonKey(name: 'hall_id') required int hallId,
    @JsonKey(name: 'airing_timestamps') required List<DateTime> airingTimestamps,
    @JsonKey(name: 'gmaps_link') required String gMapsLink,
    @JsonKey(name: 'governorate_name') required String governorateName,
    @JsonKey(name: 'area_name') required String areaName,
    @JsonKey(name: 'street_name') required String streetName,
    @JsonKey(name: 'allows_snacks') required bool allowsSnacks,
    @JsonKey(name: 'offers_snacks') required bool offersSnacks,
    @JsonKey(name: 'ticket_price') required int ticketPrice,
    @JsonKey(name: 'vip_seat_upcharge') int? vipSeatUpCharge,
    @JsonKey(name: 'rating') int? theaterRating,
  }) = _MovieAiringInfo;

  TheaterData getTheaterData() {
    return TheaterData(
      theaterName: theaterName,
      theaterPriceRange:
          vipSeatUpCharge != 0 ? "$ticketPrice-${ticketPrice + vipSeatUpCharge!} EGP" : "$ticketPrice EGP",
      theaterSnacksPolicy: allowsSnacks ? "Yes" : "No",
      offersSnacks: offersSnacks ? "Yes" : "No",
      theaterLocation: 'To be implemented',
    );
  }

  factory MovieAiringInfo.fromJson(Map<String, Object?> json) => _$MovieAiringInfoFromJson(json);
}
