import 'package:freezed_annotation/freezed_annotation.dart';
// required: associates our `main.dart` with the code generated by Freezed
part 'theater_data.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'theater_data.g.dart';

@freezed //NOTE: DEPRECATE THIS MODEL
abstract class TheaterData with _$TheaterData {
  const factory TheaterData({
    required String theaterName,
    required String theaterLocation,
    required String theaterPriceRange,
    required String theaterSnacksPolicy,
    required String offersSnacks,
  }) = _TheaterData;

  factory TheaterData.fromJson(Map<String, Object?> json) => _$TheaterDataFromJson(json);
}
